# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


MealStatistic.create(statistic:"gta_selected_beef_monday", statistic_type:'integer')
MealStatistic.create(statistic:"gta_selected_poultry_monday", statistic_type:'integer')
MealStatistic.create(statistic:"gta_selected_pork_monday", statistic_type:'integer')
MealStatistic.create(statistic:"gta_selected_green_1_monday", statistic_type:'integer')
MealStatistic.create(statistic:"gta_selected_green_2_monday", statistic_type:'integer')
MealStatistic.create(statistic:"gta_not_selected_regular_monday", statistic_type:'integer')
MealStatistic.create(statistic:"gta_not_selected_green_monday", statistic_type:'integer')
MealStatistic.create(statistic:"coffee_bar_selected_beef_monday", statistic_type:'integer')
MealStatistic.create(statistic:"coffee_bar_selected_poultry_monday", statistic_type:'integer')
MealStatistic.create(statistic:"coffee_bar_selected_pork_monday", statistic_type:'integer')
MealStatistic.create(statistic:"coffee_bar_selected_green_1_monday", statistic_type:'integer')
MealStatistic.create(statistic:"coffee_bar_selected_green_2_monday", statistic_type:'integer')
MealStatistic.create(statistic:"wandas_selected_beef_monday", statistic_type:'integer')
MealStatistic.create(statistic:"wandas_selected_poultry_monday", statistic_type:'integer')
MealStatistic.create(statistic:"wandas_selected_pork_monday", statistic_type:'integer')
MealStatistic.create(statistic:"wandas_selected_green_1_monday", statistic_type:'integer')
MealStatistic.create(statistic:"wandas_selected_green_2_monday", statistic_type:'integer')
MealStatistic.create(statistic:"gta_selected_beef_thursday", statistic_type:'integer')
MealStatistic.create(statistic:"gta_selected_poultry_thursday", statistic_type:'integer')
MealStatistic.create(statistic:"gta_selected_pork_thursday", statistic_type:'integer')
MealStatistic.create(statistic:"gta_selected_green_1_thursday", statistic_type:'integer')
MealStatistic.create(statistic:"gta_selected_green_2_thursday", statistic_type:'integer')
MealStatistic.create(statistic:"gta_not_selected_regular_thursday", statistic_type:'integer')
MealStatistic.create(statistic:"gta_not_selected_green_thursday", statistic_type:'integer')
MealStatistic.create(statistic:"coffee_bar_selected_beef_thursday", statistic_type:'integer')
MealStatistic.create(statistic:"coffee_bar_selected_poultry_thursday", statistic_type:'integer')
MealStatistic.create(statistic:"coffee_bar_selected_pork_thursday", statistic_type:'integer')
MealStatistic.create(statistic:"coffee_bar_selected_green_1_thursday", statistic_type:'integer')
MealStatistic.create(statistic:"coffee_bar_selected_green_2_thursday", statistic_type:'integer')
MealStatistic.create(statistic:"wandas_selected_beef_thursday", statistic_type:'integer')
MealStatistic.create(statistic:"wandas_selected_poultry_thursday", statistic_type:'integer')
MealStatistic.create(statistic:"wandas_selected_pork_thursday", statistic_type:'integer')
MealStatistic.create(statistic:"wandas_selected_green_1_thursday", statistic_type:'integer')
MealStatistic.create(statistic:"wandas_selected_green_2_thursday", statistic_type:'integer')
MealStatistic.create(statistic:"selected_beef_next_monday", statistic_type:'integer')
MealStatistic.create(statistic:"selected_pork_next_monday", statistic_type:'integer')
MealStatistic.create(statistic:"selected_poultry_next_monday", statistic_type:'integer')
MealStatistic.create(statistic:"selected_green_1_next_monday", statistic_type:'integer')
MealStatistic.create(statistic:"selected_green_2_next_monday", statistic_type:'integer')
MealStatistic.create(statistic:"selected_beef_next_thursday", statistic_type:'integer')
MealStatistic.create(statistic:"selected_pork_next_thursday", statistic_type:'integer')
MealStatistic.create(statistic:"selected_poultry_next_thursday", statistic_type:'integer')
MealStatistic.create(statistic:"selected_green_1_next_thursday", statistic_type:'integer')
MealStatistic.create(statistic:"selected_green_2_next_thursday", statistic_type:'integer')
MealStatistic.create(statistic:"not_selected_regular_adjustment_next_monday", statistic_type:'integer')
MealStatistic.create(statistic:"not_selected_green_adjustment_next_monday", statistic_type:'integer')
MealStatistic.create(statistic:"not_selected_regular_adjustment_next_thursday", statistic_type:'integer')
MealStatistic.create(statistic:"not_selected_green_adjustment_next_thursday", statistic_type:'integer')


