# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


MealStatistic.create(statistic:'monday_regular_red_bench',statistic_type:'integer')
MealStatistic.create(statistic:'monday_green_red_bench',statistic_type:'integer')
MealStatistic.create(statistic:'thursday_regular_red_bench',statistic_type:'integer')
MealStatistic.create(statistic:'thursday_green_red_bench',statistic_type:'integer')
MealStatistic.create(statistic:'neg_adjustment_pork_monday_red_bench',statistic_type:'integer')
MealStatistic.create(statistic:'neg_adjustment_pork_thursday_red_bench',statistic_type:'integer')
MealStatistic.create(statistic:'neg_adjustment_beef_monday_red_bench',statistic_type:'integer')
MealStatistic.create(statistic:'neg_adjustment_beef_thursday_red_bench',statistic_type:'integer')
MealStatistic.create(statistic:'neg_adjustment_poultry_monday_red_bench',statistic_type:'integer')
MealStatistic.create(statistic:'neg_adjustment_poultry_thursday_red_bench',statistic_type:'integer')
MealStatistic.create(statistic:'red_bench_meals_next_monday',statistic_type:'integer')
MealStatistic.create(statistic:'pause_next_monday_red_bench',statistic_type:'integer')
MealStatistic.create(statistic:'cancel_next_monday_red_bench',statistic_type:'integer')
MealStatistic.create(statistic:'unpause_next_monday_red_bench',statistic_type:'integer')
MealStatistic.create(statistic:'restarts_next_monday_red_bench',statistic_type:'integer')
MealStatistic.create(statistic:'meal_count_change_next_monday_red_bench',statistic_type:'integer')
MealStatistic.create(statistic:'new_sign_ups_next_monday_red_bench',statistic_type:'integer')
MealStatistic.create(statistic:'hub_change_next_monday_red_bench',statistic_type:'integer')
MealStatistic.create(statistic:'red_bench_meals_next_thursday',statistic_type:'integer')
MealStatistic.create(statistic:'pause_next_thursday_red_bench',statistic_type:'integer')
MealStatistic.create(statistic:'cancel_next_thursday_red_bench',statistic_type:'integer')
MealStatistic.create(statistic:'unpause_next_thursday_red_bench',statistic_type:'integer')
MealStatistic.create(statistic:'restarts_next_thursday_red_bench',statistic_type:'integer')
MealStatistic.create(statistic:'meal_count_change_next_thursday_red_bench',statistic_type:'integer')
MealStatistic.create(statistic:'new_sign_ups_next_thursday_red_bench',statistic_type:'integer')
MealStatistic.create(statistic:'hub_change_next_thursday_red_bench',statistic_type:'integer')
MealStatistic.create(statistic:'monday_regular_green_grind',statistic_type:'integer')
MealStatistic.create(statistic:'monday_green_green_grind',statistic_type:'integer')
MealStatistic.create(statistic:'thursday_regular_green_grind',statistic_type:'integer')
MealStatistic.create(statistic:'thursday_green_green_grind',statistic_type:'integer')
MealStatistic.create(statistic:'neg_adjustment_pork_monday_green_grind',statistic_type:'integer')
MealStatistic.create(statistic:'neg_adjustment_pork_thursday_green_grind',statistic_type:'integer')
MealStatistic.create(statistic:'neg_adjustment_beef_monday_green_grind',statistic_type:'integer')
MealStatistic.create(statistic:'neg_adjustment_beef_thursday_green_grind',statistic_type:'integer')
MealStatistic.create(statistic:'neg_adjustment_poultry_monday_green_grind',statistic_type:'integer')
MealStatistic.create(statistic:'neg_adjustment_poultry_thursday_green_grind',statistic_type:'integer')
MealStatistic.create(statistic:'green_grind_meals_next_monday',statistic_type:'integer')
MealStatistic.create(statistic:'pause_next_monday_green_grind',statistic_type:'integer')
MealStatistic.create(statistic:'cancel_next_monday_green_grind',statistic_type:'integer')
MealStatistic.create(statistic:'unpause_next_monday_green_grind',statistic_type:'integer')
MealStatistic.create(statistic:'restarts_next_monday_green_grind',statistic_type:'integer')
MealStatistic.create(statistic:'meal_count_change_next_monday_green_grind',statistic_type:'integer')
MealStatistic.create(statistic:'new_sign_ups_next_monday_green_grind',statistic_type:'integer')
MealStatistic.create(statistic:'hub_change_next_monday_green_grind',statistic_type:'integer')
MealStatistic.create(statistic:'green_grind_meals_next_thursday',statistic_type:'integer')
MealStatistic.create(statistic:'pause_next_thursday_green_grind',statistic_type:'integer')
MealStatistic.create(statistic:'cancel_next_thursday_green_grind',statistic_type:'integer')
MealStatistic.create(statistic:'unpause_next_thursday_green_grind',statistic_type:'integer')
MealStatistic.create(statistic:'restarts_next_thursday_green_grind',statistic_type:'integer')
MealStatistic.create(statistic:'meal_count_change_next_thursday_green_grind',statistic_type:'integer')
MealStatistic.create(statistic:'new_sign_ups_next_thursday_green_grind',statistic_type:'integer')
MealStatistic.create(statistic:'hub_change_next_thursday_green_grind',statistic_type:'integer')



